package top.flyfire.degetation.code;

import javassist.Modifier;

public interface Modifier2 {
	int PUBLIC = Modifier.PUBLIC;
	int PRIVATE = Modifier.PRIVATE;
	int PROTECTED = Modifier.PROTECTED;
	int STATIC = Modifier.STATIC;
	int FINAL = Modifier.FINAL;
	int SYNCHRONIZED = Modifier.SYNCHRONIZED;
	
	int PUBLIC_STATIC = PUBLIC+STATIC;
	int PUBLIC_SYNCHRONIZED = PUBLIC+SYNCHRONIZED;
	int PUBLIC_FINAL = PUBLIC+FINAL;
	
	int PUBLIC_STATIC_FINAL = PUBLIC+STATIC+FINAL;
	int PUBLIC_STATIC_SYNCHRONIZED = PUBLIC+STATIC+SYNCHRONIZED;
	
	int PUBLIC_STATIC_FINAL_SYNCHRONIZED = PUBLIC+STATIC+FINAL+SYNCHRONIZED;
	
	
	int PRIVATE_STATIC = PRIVATE+STATIC;
	int PRIVATE_SYNCHRONIZED = PRIVATE+SYNCHRONIZED;
	int PRIVATE_FINAL = PRIVATE+FINAL;
	
	int PRIVATE_STATIC_FINAL = PRIVATE+STATIC+FINAL;
	int PRIVATE_STATIC_SYNCHRONIZED = PRIVATE+STATIC+SYNCHRONIZED;
	
	int PRIVATE_STATIC_FINAL_SYNCHRONIZED = PRIVATE+STATIC+FINAL+SYNCHRONIZED;
	
	int PROTECTED_STATIC = PROTECTED+STATIC;
	int PROTECTED_SYNCHRONIZED = PROTECTED+SYNCHRONIZED;
	int PROTECTED_FINAL = PROTECTED+FINAL;
	
	int PROTECTED_STATIC_FINAL = PROTECTED+STATIC+FINAL;
	int PROTECTED_STATIC_SYNCHRONIZED = PROTECTED+STATIC+SYNCHRONIZED;
	
	int PROTECTED_STATIC_FINAL_SYNCHRONIZED = PROTECTED+STATIC+FINAL+SYNCHRONIZED;
}
